In [ ]:
10,91,59,623

In [6]:
import pandas as pd
import numpy as np

# Load the dataset
# The '../' goes up one level from 'notebooks' to the main project folder, then into 'data'
# low_memory=False helps prevent a warning about mixed data types in columns.
df = pd.read_csv('../data/loan.csv', low_memory=False)
# Display the first 5 rows to see what the data looks like
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Get a summary of the DataFrame including data types and non-null counts
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 151 columns):
 #    Column                                      Non-Null Count    Dtype
---   ------                                      --------------    -----
 0    id                                          2260701 non-null  object
 1    member_id                                   0 non-null        float64
 2    loan_amnt                                   2260668 non-null  float64
 3    funded_amnt                                 2260668 non-null  float64
 4    funded_amnt_inv                             2260668 non-null  float64
 5    term                                        2260668 non-null  object
 6    int_rate                                    2260668 non-null  float64
 7    installment                                 2260668 non-null  float64
 8    grade                                       2260668 non-null  object
 9    sub_grade                                   2260668 non-null  object
 10   emp_title                                   2093699 non-null  object
 11   emp_length                                  2113761 non-null  object
 12   home_ownership                              2260668 non-null  object
 13   annual_inc                                  2260664 non-null  float64
 14   verification_status                         2260668 non-null  object
 15   issue_d                                     2260668 non-null  object
 16   loan_status                                 2260668 non-null  object
 17   pymnt_plan                                  2260668 non-null  object
 18   url                                         2260668 non-null  object
 19   desc                                        126065 non-null   object
 20   purpose                                     2260668 non-null  object
 21   title                                       2237342 non-null  object
 22   zip_code                                    2260667 non-null  object
 23   addr_state                                  2260668 non-null  object
 24   dti                                         2258957 non-null  float64
 25   delinq_2yrs                                 2260639 non-null  float64
 26   earliest_cr_line                            2260639 non-null  object
 27   fico_range_low                              2260668 non-null  float64
 28   fico_range_high                             2260668 non-null  float64
 29   inq_last_6mths                              2260638 non-null  float64
 30   mths_since_last_delinq                      1102166 non-null  float64
 31   mths_since_last_record                      359156 non-null   float64
 32   open_acc                                    2260639 non-null  float64
 33   pub_rec                                     2260639 non-null  float64
 34   revol_bal                                   2260668 non-null  float64
 35   revol_util                                  2258866 non-null  float64
 36   total_acc                                   2260639 non-null  float64
 37   initial_list_status                         2260668 non-null  object
 38   out_prncp                                   2260668 non-null  float64
 39   out_prncp_inv                               2260668 non-null  float64
 40   total_pymnt                                 2260668 non-null  float64
 41   total_pymnt_inv                             2260668 non-null  float64
 42   total_rec_prncp                             2260668 non-null  float64
 43   total_rec_int                               2260668 non-null  float64
 44   total_rec_late_fee                          2260668 non-null  float64
 45   recoveries                                  2260668 non-null  float64
 46   collection_recovery_fee                     2260668 non-null  float64
 47   last_pymnt_d                                2258241 non-null  object
 48   last_pymnt_amnt                             2260668 non-null  float64
 49   next_pymnt_d                                915358 non-null   object
 50   last_credit_pull_d                          2260596 non-null  object
 51   last_fico_range_high                        2260668 non-null  float64
 52   last_fico_range_low                         2260668 non-null  float64
 53   collections_12_mths_ex_med                  2260523 non-null  float64
 54   mths_since_last_major_derog                 580775 non-null   float64
 55   policy_code                                 2260668 non-null  float64
 56   application_type                            2260668 non-null  object
 57   annual_inc_joint                            120710 non-null   float64
 58   dti_joint                                   120706 non-null   float64
 59   verification_status_joint                   115730 non-null   object
 60   acc_now_delinq                              2260639 non-null  float64
 61   tot_coll_amt                                2190392 non-null  float64
 62   tot_cur_bal                                 2190392 non-null  float64
 63   open_acc_6m                                 1394538 non-null  float64
 64   open_act_il                                 1394539 non-null  float64
 65   open_il_12m                                 1394539 non-null  float64
 66   open_il_24m                                 1394539 non-null  float64
 67   mths_since_rcnt_il                          1350744 non-null  float64
 68   total_bal_il                                1394539 non-null  float64
 69   il_util                                     1191818 non-null  float64
 70   open_rv_12m                                 1394539 non-null  float64
 71   open_rv_24m                                 1394539 non-null  float64
 72   max_bal_bc                                  1394539 non-null  float64
 73   all_util                                    1394320 non-null  float64
 74   total_rev_hi_lim                            2190392 non-null  float64
 75   inq_fi                                      1394539 non-null  float64
 76   total_cu_tl                                 1394538 non-null  float64
 77   inq_last_12m                                1394538 non-null  float64
 78   acc_open_past_24mths                        2210638 non-null  float64
 79   avg_cur_bal                                 2190322 non-null  float64
 80   bc_open_to_buy                              2185733 non-null  float64
 81   bc_util                                     2184597 non-null  float64
 82   chargeoff_within_12_mths                    2260523 non-null  float64
 83   delinq_amnt                                 2260639 non-null  float64
 84   mo_sin_old_il_acct                          2121597 non-null  float64
 85   mo_sin_old_rev_tl_op                        2190391 non-null  float64
 86   mo_sin_rcnt_rev_tl_op                       2190391 non-null  float64
 87   mo_sin_rcnt_tl                              2190392 non-null  float64
 88   mort_acc                                    2210638 non-null  float64
 89   mths_since_recent_bc                        2187256 non-null  float64
 90   mths_since_recent_bc_dlq                    519701 non-null   float64
 91   mths_since_recent_inq                       1965233 non-null  float64
 92   mths_since_recent_revol_delinq              740359 non-null   float64
 93   num_accts_ever_120_pd                       2190392 non-null  float64
 94   num_actv_bc_tl                              2190392 non-null  float64
 95   num_actv_rev_tl                             2190392 non-null  float64
 96   num_bc_sats                                 2202078 non-null  float64
 97   num_bc_tl                                   2190392 non-null  float64
 98   num_il_tl                                   2190392 non-null  float64
 99   num_op_rev_tl                               2190392 non-null  float64
 100  num_rev_accts                               2190391 non-null  float64
 101  num_rev_tl_bal_gt_0                         2190392 non-null  float64
 102  num_sats                                    2202078 non-null  float64
 103  num_tl_120dpd_2m                            2107011 non-null  float64
 104  num_tl_30dpd                                2190392 non-null  float64
 105  num_tl_90g_dpd_24m                          2190392 non-null  float64
 106  num_tl_op_past_12m                          2190392 non-null  float64
 107  pct_tl_nvr_dlq                              2190237 non-null  float64
 108  percent_bc_gt_75                            2185289 non-null  float64
 109  pub_rec_bankruptcies                        2259303 non-null  float64
 110  tax_liens                                   2260563 non-null  float64
 111  tot_hi_cred_lim                             2190392 non-null  float64
 112  total_bal_ex_mort                           2210638 non-null  float64
 113  total_bc_limit                              2210638 non-null  float64
 114  total_il_high_credit_limit                  2190392 non-null  float64
 115  revol_bal_joint                             108020 non-null   float64
 116  sec_app_fico_range_low                      108021 non-null   float64
 117  sec_app_fico_range_high                     108021 non-null   float64
 118  sec_app_earliest_cr_line                    108021 non-null   object
 119  sec_app_inq_last_6mths                      108021 non-null   float64
 120  sec_app_mort_acc                            108021 non-null   float64
 121  sec_app_open_acc                            108021 non-null   float64
 122  sec_app_revol_util                          106184 non-null   float64
 123  sec_app_open_act_il                         108021 non-null   float64
 124  sec_app_num_rev_accts                       108021 non-null   float64
 125  sec_app_chargeoff_within_12_mths            108021 non-null   float64
 126  sec_app_collections_12_mths_ex_med          108021 non-null   float64
 127  sec_app_mths_since_last_major_derog         35942 non-null    float64
 128  hardship_flag                               2260668 non-null  object
 129  hardship_type                               10917 non-null    object
 130  hardship_reason                             10917 non-null    object
 131  hardship_status                             10917 non-null    object
 132  deferral_term                               10917 non-null    float64
 133  hardship_amount                             10917 non-null    float64
 134  hardship_start_date                         10917 non-null    object
 135  hardship_end_date                           10917 non-null    object
 136  payment_plan_start_date                     10917 non-null    object
 137  hardship_length                             10917 non-null    float64
 138  hardship_dpd                                10917 non-null    float64
 139  hardship_loan_status                        10917 non-null    object
 140  orig_projected_additional_accrued_interest  8651 non-null     float64
 141  hardship_payoff_balance_amount              10917 non-null    float64
 142  hardship_last_payment_amount                10917 non-null    float64
 143  disbursement_method                         2260668 non-null  object
 144  debt_settlement_flag                        2260668 non-null  object
 145  debt_settlement_flag_date                   34246 non-null    object
 146  settlement_status                           34246 non-null    object
 147  settlement_date                             34246 non-null    object
 148  settlement_amount                           34246 non-null    float64
 149  settlement_percentage                       34246 non-null    float64
 150  settlement_term                             34246 non-null    float64
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [4]:
# Calculate the percentage of missing values for each column
missing_percentage = df.isnull().mean()

# Get the list of columns to drop (those with more than 40% missing data)
cols_to_drop = missing_percentage[missing_percentage > 0.4].index

# Drop these columns from the DataFrame
df.drop(columns=cols_to_drop, inplace=True)

# Check the new shape of our DataFrame
print(f"Original number of columns: {len(missing_percentage)}")
print(f"Number of columns after dropping: {df.shape[1]}")

Original number of columns: 151
Number of columns after dropping: 105

In [8]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 151 columns):
 #    Column                                      Non-Null Count    Dtype
---   ------                                      --------------    -----
 0    id                                          2260701 non-null  object
 1    member_id                                   0 non-null        float64
 2    loan_amnt                                   2260668 non-null  float64
 3    funded_amnt                                 2260668 non-null  float64
 4    funded_amnt_inv                             2260668 non-null  float64
 5    term                                        2260668 non-null  object
 6    int_rate                                    2260668 non-null  float64
 7    installment                                 2260668 non-null  float64
 8    grade                                       2260668 non-null  object
 9    sub_grade                                   2260668 non-null  object
 10   emp_title                                   2093699 non-null  object
 11   emp_length                                  2113761 non-null  object
 12   home_ownership                              2260668 non-null  object
 13   annual_inc                                  2260664 non-null  float64
 14   verification_status                         2260668 non-null  object
 15   issue_d                                     2260668 non-null  object
 16   loan_status                                 2260668 non-null  object
 17   pymnt_plan                                  2260668 non-null  object
 18   url                                         2260668 non-null  object
 19   desc                                        126065 non-null   object
 20   purpose                                     2260668 non-null  object
 21   title                                       2237342 non-null  object
 22   zip_code                                    2260667 non-null  object
 23   addr_state                                  2260668 non-null  object
 24   dti                                         2258957 non-null  float64
 25   delinq_2yrs                                 2260639 non-null  float64
 26   earliest_cr_line                            2260639 non-null  object
 27   fico_range_low                              2260668 non-null  float64
 28   fico_range_high                             2260668 non-null  float64
 29   inq_last_6mths                              2260638 non-null  float64
 30   mths_since_last_delinq                      1102166 non-null  float64
 31   mths_since_last_record                      359156 non-null   float64
 32   open_acc                                    2260639 non-null  float64
 33   pub_rec                                     2260639 non-null  float64
 34   revol_bal                                   2260668 non-null  float64
 35   revol_util                                  2258866 non-null  float64
 36   total_acc                                   2260639 non-null  float64
 37   initial_list_status                         2260668 non-null  object
 38   out_prncp                                   2260668 non-null  float64
 39   out_prncp_inv                               2260668 non-null  float64
 40   total_pymnt                                 2260668 non-null  float64
 41   total_pymnt_inv                             2260668 non-null  float64
 42   total_rec_prncp                             2260668 non-null  float64
 43   total_rec_int                               2260668 non-null  float64
 44   total_rec_late_fee                          2260668 non-null  float64
 45   recoveries                                  2260668 non-null  float64
 46   collection_recovery_fee                     2260668 non-null  float64
 47   last_pymnt_d                                2258241 non-null  object
 48   last_pymnt_amnt                             2260668 non-null  float64
 49   next_pymnt_d                                915358 non-null   object
 50   last_credit_pull_d                          2260596 non-null  object
 51   last_fico_range_high                        2260668 non-null  float64
 52   last_fico_range_low                         2260668 non-null  float64
 53   collections_12_mths_ex_med                  2260523 non-null  float64
 54   mths_since_last_major_derog                 580775 non-null   float64
 55   policy_code                                 2260668 non-null  float64
 56   application_type                            2260668 non-null  object
 57   annual_inc_joint                            120710 non-null   float64
 58   dti_joint                                   120706 non-null   float64
 59   verification_status_joint                   115730 non-null   object
 60   acc_now_delinq                              2260639 non-null  float64
 61   tot_coll_amt                                2190392 non-null  float64
 62   tot_cur_bal                                 2190392 non-null  float64
 63   open_acc_6m                                 1394538 non-null  float64
 64   open_act_il                                 1394539 non-null  float64
 65   open_il_12m                                 1394539 non-null  float64
 66   open_il_24m                                 1394539 non-null  float64
 67   mths_since_rcnt_il                          1350744 non-null  float64
 68   total_bal_il                                1394539 non-null  float64
 69   il_util                                     1191818 non-null  float64
 70   open_rv_12m                                 1394539 non-null  float64
 71   open_rv_24m                                 1394539 non-null  float64
 72   max_bal_bc                                  1394539 non-null  float64
 73   all_util                                    1394320 non-null  float64
 74   total_rev_hi_lim                            2190392 non-null  float64
 75   inq_fi                                      1394539 non-null  float64
 76   total_cu_tl                                 1394538 non-null  float64
 77   inq_last_12m                                1394538 non-null  float64
 78   acc_open_past_24mths                        2210638 non-null  float64
 79   avg_cur_bal                                 2190322 non-null  float64
 80   bc_open_to_buy                              2185733 non-null  float64
 81   bc_util                                     2184597 non-null  float64
 82   chargeoff_within_12_mths                    2260523 non-null  float64
 83   delinq_amnt                                 2260639 non-null  float64
 84   mo_sin_old_il_acct                          2121597 non-null  float64
 85   mo_sin_old_rev_tl_op                        2190391 non-null  float64
 86   mo_sin_rcnt_rev_tl_op                       2190391 non-null  float64
 87   mo_sin_rcnt_tl                              2190392 non-null  float64
 88   mort_acc                                    2210638 non-null  float64
 89   mths_since_recent_bc                        2187256 non-null  float64
 90   mths_since_recent_bc_dlq                    519701 non-null   float64
 91   mths_since_recent_inq                       1965233 non-null  float64
 92   mths_since_recent_revol_delinq              740359 non-null   float64
 93   num_accts_ever_120_pd                       2190392 non-null  float64
 94   num_actv_bc_tl                              2190392 non-null  float64
 95   num_actv_rev_tl                             2190392 non-null  float64
 96   num_bc_sats                                 2202078 non-null  float64
 97   num_bc_tl                                   2190392 non-null  float64
 98   num_il_tl                                   2190392 non-null  float64
 99   num_op_rev_tl                               2190392 non-null  float64
 100  num_rev_accts                               2190391 non-null  float64
 101  num_rev_tl_bal_gt_0                         2190392 non-null  float64
 102  num_sats                                    2202078 non-null  float64
 103  num_tl_120dpd_2m                            2107011 non-null  float64
 104  num_tl_30dpd                                2190392 non-null  float64
 105  num_tl_90g_dpd_24m                          2190392 non-null  float64
 106  num_tl_op_past_12m                          2190392 non-null  float64
 107  pct_tl_nvr_dlq                              2190237 non-null  float64
 108  percent_bc_gt_75                            2185289 non-null  float64
 109  pub_rec_bankruptcies                        2259303 non-null  float64
 110  tax_liens                                   2260563 non-null  float64
 111  tot_hi_cred_lim                             2190392 non-null  float64
 112  total_bal_ex_mort                           2210638 non-null  float64
 113  total_bc_limit                              2210638 non-null  float64
 114  total_il_high_credit_limit                  2190392 non-null  float64
 115  revol_bal_joint                             108020 non-null   float64
 116  sec_app_fico_range_low                      108021 non-null   float64
 117  sec_app_fico_range_high                     108021 non-null   float64
 118  sec_app_earliest_cr_line                    108021 non-null   object
 119  sec_app_inq_last_6mths                      108021 non-null   float64
 120  sec_app_mort_acc                            108021 non-null   float64
 121  sec_app_open_acc                            108021 non-null   float64
 122  sec_app_revol_util                          106184 non-null   float64
 123  sec_app_open_act_il                         108021 non-null   float64
 124  sec_app_num_rev_accts                       108021 non-null   float64
 125  sec_app_chargeoff_within_12_mths            108021 non-null   float64
 126  sec_app_collections_12_mths_ex_med          108021 non-null   float64
 127  sec_app_mths_since_last_major_derog         35942 non-null    float64
 128  hardship_flag                               2260668 non-null  object
 129  hardship_type                               10917 non-null    object
 130  hardship_reason                             10917 non-null    object
 131  hardship_status                             10917 non-null    object
 132  deferral_term                               10917 non-null    float64
 133  hardship_amount                             10917 non-null    float64
 134  hardship_start_date                         10917 non-null    object
 135  hardship_end_date                           10917 non-null    object
 136  payment_plan_start_date                     10917 non-null    object
 137  hardship_length                             10917 non-null    float64
 138  hardship_dpd                                10917 non-null    float64
 139  hardship_loan_status                        10917 non-null    object
 140  orig_projected_additional_accrued_interest  8651 non-null     float64
 141  hardship_payoff_balance_amount              10917 non-null    float64
 142  hardship_last_payment_amount                10917 non-null    float64
 143  disbursement_method                         2260668 non-null  object
 144  debt_settlement_flag                        2260668 non-null  object
 145  debt_settlement_flag_date                   34246 non-null    object
 146  settlement_status                           34246 non-null    object
 147  settlement_date                             34246 non-null    object
 148  settlement_amount                           34246 non-null    float64
 149  settlement_percentage                       34246 non-null    float64
 150  settlement_term                             34246 non-null    float64
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [9]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Clean 'int_rate': remove '%' and convert to float
# df['int_rate'] = df['int_rate'].str.replace('%', '').astype(float)

# See how many rows have a missing term
print("Number of missing terms:", df['term'].isnull().sum())
print("Total rows:", len(df))

# If the number is small, drop them
# df.dropna(subset=['term'], inplace=True)

# Now this conversion will work without error
# df['term'] = df['term'].str.replace(' months', '').astype(int)

# Clean 'emp_length': extract the numbers. We'll fill missing values with 0.
# This uses a regular expression to find the digits.
# df['emp_length'] = df['emp_length'].str.extract('(\d+)').astype(float)
df['emp_length'] = df['emp_length'].fillna(0) # Assume missing means 0 years experience or unemployed

Number of missing terms: 0
Total rows: 2260668

In [15]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 2260668 entries, 0 to 2260698
Data columns (total 151 columns):
 #    Column                                      Non-Null Count    Dtype
---   ------                                      --------------    -----
 0    id                                          2260668 non-null  object
 1    member_id                                   0 non-null        float64
 2    loan_amnt                                   2260668 non-null  float64
 3    funded_amnt                                 2260668 non-null  float64
 4    funded_amnt_inv                             2260668 non-null  float64
 5    term                                        2260668 non-null  int64
 6    int_rate                                    2260668 non-null  float64
 7    installment                                 2260668 non-null  float64
 8    grade                                       2260668 non-null  object
 9    sub_grade                                   2260668 non-null  object
 10   emp_title                                   2093699 non-null  object
 11   emp_length                                  2260668 non-null  float64
 12   home_ownership                              2260668 non-null  object
 13   annual_inc                                  2260664 non-null  float64
 14   verification_status                         2260668 non-null  object
 15   issue_d                                     2260668 non-null  object
 16   loan_status                                 2260668 non-null  object
 17   pymnt_plan                                  2260668 non-null  object
 18   url                                         2260668 non-null  object
 19   desc                                        126065 non-null   object
 20   purpose                                     2260668 non-null  object
 21   title                                       2237342 non-null  object
 22   zip_code                                    2260667 non-null  object
 23   addr_state                                  2260668 non-null  object
 24   dti                                         2258957 non-null  float64
 25   delinq_2yrs                                 2260639 non-null  float64
 26   earliest_cr_line                            2260639 non-null  object
 27   fico_range_low                              2260668 non-null  float64
 28   fico_range_high                             2260668 non-null  float64
 29   inq_last_6mths                              2260638 non-null  float64
 30   mths_since_last_delinq                      1102166 non-null  float64
 31   mths_since_last_record                      359156 non-null   float64
 32   open_acc                                    2260639 non-null  float64
 33   pub_rec                                     2260639 non-null  float64
 34   revol_bal                                   2260668 non-null  float64
 35   revol_util                                  2258866 non-null  float64
 36   total_acc                                   2260639 non-null  float64
 37   initial_list_status                         2260668 non-null  object
 38   out_prncp                                   2260668 non-null  float64
 39   out_prncp_inv                               2260668 non-null  float64
 40   total_pymnt                                 2260668 non-null  float64
 41   total_pymnt_inv                             2260668 non-null  float64
 42   total_rec_prncp                             2260668 non-null  float64
 43   total_rec_int                               2260668 non-null  float64
 44   total_rec_late_fee                          2260668 non-null  float64
 45   recoveries                                  2260668 non-null  float64
 46   collection_recovery_fee                     2260668 non-null  float64
 47   last_pymnt_d                                2258241 non-null  object
 48   last_pymnt_amnt                             2260668 non-null  float64
 49   next_pymnt_d                                915358 non-null   object
 50   last_credit_pull_d                          2260596 non-null  object
 51   last_fico_range_high                        2260668 non-null  float64
 52   last_fico_range_low                         2260668 non-null  float64
 53   collections_12_mths_ex_med                  2260523 non-null  float64
 54   mths_since_last_major_derog                 580775 non-null   float64
 55   policy_code                                 2260668 non-null  float64
 56   application_type                            2260668 non-null  object
 57   annual_inc_joint                            120710 non-null   float64
 58   dti_joint                                   120706 non-null   float64
 59   verification_status_joint                   115730 non-null   object
 60   acc_now_delinq                              2260639 non-null  float64
 61   tot_coll_amt                                2190392 non-null  float64
 62   tot_cur_bal                                 2190392 non-null  float64
 63   open_acc_6m                                 1394538 non-null  float64
 64   open_act_il                                 1394539 non-null  float64
 65   open_il_12m                                 1394539 non-null  float64
 66   open_il_24m                                 1394539 non-null  float64
 67   mths_since_rcnt_il                          1350744 non-null  float64
 68   total_bal_il                                1394539 non-null  float64
 69   il_util                                     1191818 non-null  float64
 70   open_rv_12m                                 1394539 non-null  float64
 71   open_rv_24m                                 1394539 non-null  float64
 72   max_bal_bc                                  1394539 non-null  float64
 73   all_util                                    1394320 non-null  float64
 74   total_rev_hi_lim                            2190392 non-null  float64
 75   inq_fi                                      1394539 non-null  float64
 76   total_cu_tl                                 1394538 non-null  float64
 77   inq_last_12m                                1394538 non-null  float64
 78   acc_open_past_24mths                        2210638 non-null  float64
 79   avg_cur_bal                                 2190322 non-null  float64
 80   bc_open_to_buy                              2185733 non-null  float64
 81   bc_util                                     2184597 non-null  float64
 82   chargeoff_within_12_mths                    2260523 non-null  float64
 83   delinq_amnt                                 2260639 non-null  float64
 84   mo_sin_old_il_acct                          2121597 non-null  float64
 85   mo_sin_old_rev_tl_op                        2190391 non-null  float64
 86   mo_sin_rcnt_rev_tl_op                       2190391 non-null  float64
 87   mo_sin_rcnt_tl                              2190392 non-null  float64
 88   mort_acc                                    2210638 non-null  float64
 89   mths_since_recent_bc                        2187256 non-null  float64
 90   mths_since_recent_bc_dlq                    519701 non-null   float64
 91   mths_since_recent_inq                       1965233 non-null  float64
 92   mths_since_recent_revol_delinq              740359 non-null   float64
 93   num_accts_ever_120_pd                       2190392 non-null  float64
 94   num_actv_bc_tl                              2190392 non-null  float64
 95   num_actv_rev_tl                             2190392 non-null  float64
 96   num_bc_sats                                 2202078 non-null  float64
 97   num_bc_tl                                   2190392 non-null  float64
 98   num_il_tl                                   2190392 non-null  float64
 99   num_op_rev_tl                               2190392 non-null  float64
 100  num_rev_accts                               2190391 non-null  float64
 101  num_rev_tl_bal_gt_0                         2190392 non-null  float64
 102  num_sats                                    2202078 non-null  float64
 103  num_tl_120dpd_2m                            2107011 non-null  float64
 104  num_tl_30dpd                                2190392 non-null  float64
 105  num_tl_90g_dpd_24m                          2190392 non-null  float64
 106  num_tl_op_past_12m                          2190392 non-null  float64
 107  pct_tl_nvr_dlq                              2190237 non-null  float64
 108  percent_bc_gt_75                            2185289 non-null  float64
 109  pub_rec_bankruptcies                        2259303 non-null  float64
 110  tax_liens                                   2260563 non-null  float64
 111  tot_hi_cred_lim                             2190392 non-null  float64
 112  total_bal_ex_mort                           2210638 non-null  float64
 113  total_bc_limit                              2210638 non-null  float64
 114  total_il_high_credit_limit                  2190392 non-null  float64
 115  revol_bal_joint                             108020 non-null   float64
 116  sec_app_fico_range_low                      108021 non-null   float64
 117  sec_app_fico_range_high                     108021 non-null   float64
 118  sec_app_earliest_cr_line                    108021 non-null   object
 119  sec_app_inq_last_6mths                      108021 non-null   float64
 120  sec_app_mort_acc                            108021 non-null   float64
 121  sec_app_open_acc                            108021 non-null   float64
 122  sec_app_revol_util                          106184 non-null   float64
 123  sec_app_open_act_il                         108021 non-null   float64
 124  sec_app_num_rev_accts                       108021 non-null   float64
 125  sec_app_chargeoff_within_12_mths            108021 non-null   float64
 126  sec_app_collections_12_mths_ex_med          108021 non-null   float64
 127  sec_app_mths_since_last_major_derog         35942 non-null    float64
 128  hardship_flag                               2260668 non-null  object
 129  hardship_type                               10917 non-null    object
 130  hardship_reason                             10917 non-null    object
 131  hardship_status                             10917 non-null    object
 132  deferral_term                               10917 non-null    float64
 133  hardship_amount                             10917 non-null    float64
 134  hardship_start_date                         10917 non-null    object
 135  hardship_end_date                           10917 non-null    object
 136  payment_plan_start_date                     10917 non-null    object
 137  hardship_length                             10917 non-null    float64
 138  hardship_dpd                                10917 non-null    float64
 139  hardship_loan_status                        10917 non-null    object
 140  orig_projected_additional_accrued_interest  8651 non-null     float64
 141  hardship_payoff_balance_amount              10917 non-null    float64
 142  hardship_last_payment_amount                10917 non-null    float64
 143  disbursement_method                         2260668 non-null  object
 144  debt_settlement_flag                        2260668 non-null  object
 145  debt_settlement_flag_date                   34246 non-null    object
 146  settlement_status                           34246 non-null    object
 147  settlement_date                             34246 non-null    object
 148  settlement_amount                           34246 non-null    float64
 149  settlement_percentage                       34246 non-null    float64
 150  settlement_term                             34246 non-null    float64
dtypes: float64(114), int64(1), object(36)
memory usage: 2.6+ GB

In [16]:
# See the different values in the 'loan_status' column
print(df['loan_status'].value_counts())

# Define what constitutes a "bad loan"
bad_loan_statuses = ['Charged Off', 'Default', 'Does not meet the credit policy. Status:Charged Off', 'Late (31-120 days)']

# Create our target variable: 1 for a bad loan, 0 for a good loan
df['is_bad_loan'] = np.where(df['loan_status'].isin(bad_loan_statuses), 1, 0)

# See the distribution of our new target variable
print(df['is_bad_loan'].value_counts(normalize=True))

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64
is_bad_loan
0    0.871354
1    0.128646
Name: proportion, dtype: float64

In [17]:
# Save the cleaned DataFrame to a new file in the data directory
df.to_csv('../data/processed_data.csv', index=False)